### PR TITLE
Detect if root project (or git projects) are also available on NPM

### PR DESCRIPTION
**Pull request by tekeuange23**
Insert the pacode request on manifest data  at the `line 130` in `/src/deoWalker.js`

### CODE REVIEW

**Review by fraxken — APPROVED** [review]
LGTM

**Comment by tekeuange23** [comment]
Apart from the test which fail

**Comment by fraxken** [comment]
@tekeuange23 I think you need to update the snapshot (cause you'r adding a new information here so the snapshot is not the same anymore)

**Comment by tekeuange23** [comment]
Yeah I see

**Comment by tekeuange23** [comment]
Snapshot fixed!

**Comment by fraxken** [comment]
@all-contributors please add @tekeuange23 for code

**Pull request merged**
