### PR TITLE
Type synch for @nodesecure/js-x-ray

### PR DESCRIPTION
**Pull request by Aekk0**
based on https://github.com/NodeSecure/scanner/issues/60

### CODE REVIEW

**Comment by fraxken** [comment]
Do you need a release of JS-X-Ray to update the package here ? @Aekk0

**Comment by fraxken** [comment]
New version 5.1.0 of JS-X-Ray has been released (if required).

**Comment by Aekk0** [comment]
It wasn't necessary since it was only typage modification on JS-X-Ray side.
Yet as there were no breaking changes, updated to 5.1.0

**Comment by fraxken** [comment]
@all-contributors please add @Aekk0 for code

**Pull request merged**
